# Generated by Django 3.0.8 on 2020-08-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=20)),
                ('start_position1', models.IntegerField(blank=True)),
                ('is_across1', models.BooleanField(default=True)),
                ('word2', models.CharField(max_length=20)),
                ('start_position2', models.IntegerField(blank=True)),
                ('is_across2', models.BooleanField(default=True)),
                ('word3', models.CharField(max_length=20)),
                ('start_position3', models.IntegerField(blank=True)),
                ('is_across3', models.BooleanField(default=True)),
                ('word4', models.CharField(max_length=20)),
                ('start_position4', models.IntegerField(blank=True)),
                ('is_across4', models.BooleanField(default=True)),
                ('word5', models.CharField(max_length=20)),
                ('start_position5', models.IntegerField(blank=True)),
                ('is_across5', models.BooleanField(default=True)),
                ('word6', models.CharField(max_length=20)),
                ('start_position6', models.IntegerField(blank=True)),
                ('is_across6', models.BooleanField(default=True)),
                ('word7', models.CharField(max_length=20)),
                ('start_position7', models.IntegerField(blank=True)),
                ('is_across7', models.BooleanField(default=True)),
                ('word8', models.CharField(max_length=20)),
                ('start_position8', models.IntegerField(blank=True)),
                ('is_across8', models.BooleanField(default=True)),
                ('word9', models.CharField(max_length=20)),
                ('start_position9', models.IntegerField(blank=True)),
                ('is_across9', models.BooleanField(default=True)),
                ('word10', models.CharField(max_length=20)),
                ('start_position10', models.IntegerField(blank=True)),
                ('is_across10', models.BooleanField(default=True)),
                ('word11', models.CharField(max_length=20)),
                ('start_position11', models.IntegerField(blank=True)),
                ('is_across11', models.BooleanField(default=True)),
                ('word12', models.CharField(max_length=20)),
                ('start_position12', models.IntegerField(blank=True)),
                ('is_across12', models.BooleanField(default=True)),
                ('word13', models.CharField(max_length=20)),
                ('start_position13', models.IntegerField(blank=True)),
                ('is_across13', models.BooleanField(default=True)),
                ('word14', models.CharField(max_length=20)),
                ('start_position14', models.IntegerField(blank=True)),
                ('is_across14', models.BooleanField(default=True)),
                ('word15', models.CharField(max_length=20)),
                ('start_position15', models.IntegerField(blank=True)),
                ('is_across15', models.BooleanField(default=True)),
                ('word16', models.CharField(max_length=20)),
                ('start_position16', models.IntegerField(blank=True)),
                ('is_across16', models.BooleanField(default=True)),
                ('word17', models.CharField(max_length=20)),
                ('start_position17', models.IntegerField(blank=True)),
                ('is_across17', models.BooleanField(default=True)),
                ('word18', models.CharField(max_length=20)),
                ('start_position18', models.IntegerField(blank=True)),
                ('is_across18', models.BooleanField(default=True)),
            ],
        ),
    ]
