# Generated by Django 3.0.8 on 2020-08-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0002_auto_20200812_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='start_position_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='crossword',
            name='start_position_y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
