# Generated by Django 3.0.8 on 2020-08-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0003_auto_20200812_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosswordcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True)),
                ('email', models.CharField(max_length=200)),
                ('subscribe_yes', models.BooleanField(default=True)),
            ],
        ),
    ]
