# Generated by Django 3.0.8 on 2020-08-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0005_crosswordcheck_contest_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordcheck',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
