from django.db import models

class Latest(models.Model):
  
  published_date = models.DateField(blank=True)
  is_published = models.BooleanField(default=True)
  abstract = models.TextField(blank=True)
  ### section 1#####
  section_heading1 = models.CharField(max_length=200, blank=True)
  image1_1 = models.ImageField(blank=True)
  title1_1 = models.CharField(max_length=200)
  content1_1 = models.TextField()
  word1_1_1 = models.CharField(max_length=200, blank=True)
  link1_1_1 = models.TextField(blank=True)
  word1_1_2 = models.CharField(max_length=200, blank=True)
  link1_1_2 = models.TextField(blank=True)
  word1_1_3 = models.CharField(max_length=200, blank=True)
  link1_1_3 = models.TextField(blank=True)
  s_link1_1_1 = models.TextField(blank=True)
  s_link1_1_2 = models.TextField(blank=True)
  
  image1_2 = models.ImageField(blank=True)
  title1_2 = models.CharField(max_length=200)
  content1_2 = models.TextField()
  word1_2_1 = models.CharField(max_length=200, blank=True)
  link1_2_1 = models.TextField(blank=True)
  word1_2_2 = models.CharField(max_length=200, blank=True)
  link1_2_2 = models.TextField(blank=True)
  word1_2_3 = models.CharField(max_length=200, blank=True)
  link1_2_3 = models.TextField(blank=True)
  s_link1_2_1 = models.TextField(blank=True)
  s_link1_2_2 = models.TextField(blank=True)

  image1_3 = models.ImageField(blank=True)
  title1_3 = models.CharField(max_length=200)
  content1_3 = models.TextField()
  word1_3_1 = models.CharField(max_length=200, blank=True)
  link1_3_1 = models.TextField(blank=True)
  word1_3_2 = models.CharField(max_length=200, blank=True)
  link1_3_2 = models.TextField(blank=True)
  word1_3_3 = models.CharField(max_length=200, blank=True)
  link1_3_3 = models.TextField(blank=True)
  s_link1_3_1 = models.TextField(blank=True)
  s_link1_3_2 = models.TextField(blank=True)

  image1_4 = models.ImageField(blank=True)
  title1_4 = models.CharField(max_length=200)
  content1_4 = models.TextField()
  word1_4_1 = models.CharField(max_length=200, blank=True)
  link1_4_1 = models.TextField(blank=True)
  word1_4_2 = models.CharField(max_length=200, blank=True)
  link1_4_2 = models.TextField(blank=True)
  word1_4_3 = models.CharField(max_length=200, blank=True)
  link1_4_3 = models.TextField(blank=True)
  s_link1_4_1 = models.TextField(blank=True)
  s_link1_4_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)

########

  section_heading2 = models.CharField(max_length=200, blank=True)
  image2_1 = models.ImageField(blank=True)
  title2_1 = models.CharField(max_length=200)
  content2_1 = models.TextField()
  word2_1_1 = models.CharField(max_length=200, blank=True)
  link2_1_1 = models.TextField(blank=True)
  word2_1_2 = models.CharField(max_length=200, blank=True)
  link2_1_2 = models.TextField(blank=True)
  word1_1_3 = models.CharField(max_length=200, blank=True)
  link2_1_3 = models.TextField(blank=True)
  s_link2_1_1 = models.TextField(blank=True)
  s_link2_1_2 = models.TextField(blank=True)
  
  image2_2 = models.ImageField(blank=True)
  title2_2 = models.CharField(max_length=200)
  content2_2 = models.TextField()
  word2_2_1 = models.CharField(max_length=200, blank=True)
  link2_2_1 = models.TextField(blank=True)
  word2_2_2 = models.CharField(max_length=200, blank=True)
  link2_2_2 = models.TextField(blank=True)
  word2_2_3 = models.CharField(max_length=200, blank=True)
  link2_2_3 = models.TextField(blank=True)
  s_link2_2_1 = models.TextField(blank=True)
  s_link2_2_2 = models.TextField(blank=True)

  image2_3 = models.ImageField(blank=True)
  title2_3 = models.CharField(max_length=200)
  content2_3 = models.TextField()
  word2_3_1 = models.CharField(max_length=200, blank=True)
  link2_3_1 = models.TextField(blank=True)
  word2_3_2 = models.CharField(max_length=200, blank=True)
  link2_3_2 = models.TextField(blank=True)
  word2_3_3 = models.CharField(max_length=200, blank=True)
  link2_3_3 = models.TextField(blank=True)
  s_link2_3_1 = models.TextField(blank=True)
  s_link2_3_2 = models.TextField(blank=True)

  image2_4 = models.ImageField(blank=True)
  title2_4 = models.CharField(max_length=200)
  content2_4 = models.TextField()
  word2_4_1 = models.CharField(max_length=200, blank=True)
  link2_4_1 = models.TextField(blank=True)
  word2_4_2 = models.CharField(max_length=200, blank=True)
  link2_4_2 = models.TextField(blank=True)
  word2_4_3 = models.CharField(max_length=200, blank=True)
  link2_4_3 = models.TextField(blank=True)
  s_link2_4_1 = models.TextField(blank=True)
  s_link2_4_2 = models.TextField(blank=True)

  image2_5 = models.ImageField(blank=True)
  title2_5 = models.CharField(max_length=200)
  content2_5 = models.TextField()
  word2_5_1 = models.CharField(max_length=200, blank=True)
  link2_5_1 = models.TextField(blank=True)
  word2_5_2 = models.CharField(max_length=200, blank=True)
  link2_5_2 = models.TextField(blank=True)
  word2_5_3 = models.CharField(max_length=200, blank=True)
  link2_5_3 = models.TextField(blank=True)
  s_link2_5_1 = models.TextField(blank=True)
  s_link2_5_2 = models.TextField(blank=True)

######

  section_heading3 = models.CharField(max_length=200, blank=True)
  image3_1 = models.ImageField(blank=True)
  title3_1 = models.CharField(max_length=200)
  content3_1 = models.TextField()
  word3_1_1 = models.CharField(max_length=200, blank=True)
  link3_1_1 = models.TextField(blank=True)
  word3_1_2 = models.CharField(max_length=200, blank=True)
  link3_1_2 = models.TextField(blank=True)
  word1_1_3 = models.CharField(max_length=200, blank=True)
  link1_1_3 = models.TextField(blank=True)
  s_link1_1_1 = models.TextField(blank=True)
  s_link1_1_2 = models.TextField(blank=True)
  
  image1_2 = models.ImageField(blank=True)
  title1_2 = models.CharField(max_length=200)
  content1_2 = models.TextField()
  word1_2_1 = models.CharField(max_length=200, blank=True)
  link1_2_1 = models.TextField(blank=True)
  word1_2_2 = models.CharField(max_length=200, blank=True)
  link1_2_2 = models.TextField(blank=True)
  word1_2_3 = models.CharField(max_length=200, blank=True)
  link1_2_3 = models.TextField(blank=True)
  s_link1_2_1 = models.TextField(blank=True)
  s_link1_2_2 = models.TextField(blank=True)

  image1_3 = models.ImageField(blank=True)
  title1_3 = models.CharField(max_length=200)
  content1_3 = models.TextField()
  word1_3_1 = models.CharField(max_length=200, blank=True)
  link1_3_1 = models.TextField(blank=True)
  word1_3_2 = models.CharField(max_length=200, blank=True)
  link1_3_2 = models.TextField(blank=True)
  word1_3_3 = models.CharField(max_length=200, blank=True)
  link1_3_3 = models.TextField(blank=True)
  s_link1_3_1 = models.TextField(blank=True)
  s_link1_3_2 = models.TextField(blank=True)

  image1_4 = models.ImageField(blank=True)
  title1_4 = models.CharField(max_length=200)
  content1_4 = models.TextField()
  word1_4_1 = models.CharField(max_length=200, blank=True)
  link1_4_1 = models.TextField(blank=True)
  word1_4_2 = models.CharField(max_length=200, blank=True)
  link1_4_2 = models.TextField(blank=True)
  word1_4_3 = models.CharField(max_length=200, blank=True)
  link1_4_3 = models.TextField(blank=True)
  s_link1_4_1 = models.TextField(blank=True)
  s_link1_4_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)

#####
  section_heading1 = models.CharField(max_length=200, blank=True)
  image1_1 = models.ImageField(blank=True)
  title1_1 = models.CharField(max_length=200)
  content1_1 = models.TextField()
  word1_1_1 = models.CharField(max_length=200, blank=True)
  link1_1_1 = models.TextField(blank=True)
  word1_1_2 = models.CharField(max_length=200, blank=True)
  link1_1_2 = models.TextField(blank=True)
  word1_1_3 = models.CharField(max_length=200, blank=True)
  link1_1_3 = models.TextField(blank=True)
  s_link1_1_1 = models.TextField(blank=True)
  s_link1_1_2 = models.TextField(blank=True)
  
  image1_2 = models.ImageField(blank=True)
  title1_2 = models.CharField(max_length=200)
  content1_2 = models.TextField()
  word1_2_1 = models.CharField(max_length=200, blank=True)
  link1_2_1 = models.TextField(blank=True)
  word1_2_2 = models.CharField(max_length=200, blank=True)
  link1_2_2 = models.TextField(blank=True)
  word1_2_3 = models.CharField(max_length=200, blank=True)
  link1_2_3 = models.TextField(blank=True)
  s_link1_2_1 = models.TextField(blank=True)
  s_link1_2_2 = models.TextField(blank=True)

  image1_3 = models.ImageField(blank=True)
  title1_3 = models.CharField(max_length=200)
  content1_3 = models.TextField()
  word1_3_1 = models.CharField(max_length=200, blank=True)
  link1_3_1 = models.TextField(blank=True)
  word1_3_2 = models.CharField(max_length=200, blank=True)
  link1_3_2 = models.TextField(blank=True)
  word1_3_3 = models.CharField(max_length=200, blank=True)
  link1_3_3 = models.TextField(blank=True)
  s_link1_3_1 = models.TextField(blank=True)
  s_link1_3_2 = models.TextField(blank=True)

  image1_4 = models.ImageField(blank=True)
  title1_4 = models.CharField(max_length=200)
  content1_4 = models.TextField()
  word1_4_1 = models.CharField(max_length=200, blank=True)
  link1_4_1 = models.TextField(blank=True)
  word1_4_2 = models.CharField(max_length=200, blank=True)
  link1_4_2 = models.TextField(blank=True)
  word1_4_3 = models.CharField(max_length=200, blank=True)
  link1_4_3 = models.TextField(blank=True)
  s_link1_4_1 = models.TextField(blank=True)
  s_link1_4_2 = models.TextField(blank=True)

  image1_5 = models.ImageField(blank=True)
  title1_5 = models.CharField(max_length=200)
  content1_5 = models.TextField()
  word1_5_1 = models.CharField(max_length=200, blank=True)
  link1_5_1 = models.TextField(blank=True)
  word1_5_2 = models.CharField(max_length=200, blank=True)
  link1_5_2 = models.TextField(blank=True)
  word1_5_3 = models.CharField(max_length=200, blank=True)
  link1_5_3 = models.TextField(blank=True)
  s_link1_5_1 = models.TextField(blank=True)
  s_link1_5_2 = models.TextField(blank=True)



  published_date = models.DateField(blank=True)
  main_heading = models.IntegerField(default=0)
  content = models.TextField()
  is_published = models.BooleanField(default=True)
  word1 = models.CharField(max_length=200, blank=True)
  link1 = models.TextField(blank=True)
  word2 = models.CharField(max_length=200, blank=True)
  link2 = models.TextField(blank=True)
  word3 = models.CharField(max_length=200, blank=True)
  link3 = models.TextField(blank=True)
  s_link1 = models.TextField(blank=True)
  s_link2 = models.TextField(blank=True)
  s_link3 = models.TextField(blank=True)
  s_link4 = models.TextField(blank=True)
  image = models.ImageField(blank=True)


  def __str__(self):
    return self.title
