# Generated by Django 3.0.8 on 2020-08-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytitle',
            name='wish_to_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
