# Generated by Django 3.0.8 on 2020-07-06 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscontent',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
