# Generated by Django 3.0.8 on 2020-07-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0004_auto_20200716_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscontent',
            old_name='link',
            new_name='link1',
        ),
        migrations.RenameField(
            model_name='newscontent',
            old_name='word',
            new_name='word1',
        ),
        migrations.AddField(
            model_name='newscontent',
            name='link2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='link3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='s_link1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='s_link2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='s_link3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='s_link4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='word2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='word3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
