# Generated by Django 3.0.8 on 2020-07-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0006_newscontent_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscontent',
            name='main_heading',
            field=models.IntegerField(default=0),
        ),
    ]
