# Generated by Django 3.0.8 on 2020-07-27 06:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0006_newscontent_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
