# Generated by Django 3.0.8 on 2020-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='title1_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title1_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title1_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title1_4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title2_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title2_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title2_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title2_4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_6',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_7',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title3_8',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title5_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title5_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title5_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title5_4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='title5_5',
            field=models.CharField(default='', max_length=200),
        ),
    ]
