# Generated by Django 3.0.8 on 2020-07-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest', '0002_auto_20200727_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='image_credits1_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits1_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits1_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits1_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits2_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits2_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits2_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits2_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='latest',
            name='image_credits3_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image1_1',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image1_2',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image1_3',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image1_4',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image2_1',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image2_2',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image2_3',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image2_4',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_1',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_2',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_3',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_4',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_5',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_6',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_7',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image3_8',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title1_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title1_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title1_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title1_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title2_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title2_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title2_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title2_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title3_8',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
