# Generated by Django 3.0.8 on 2020-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest', '0003_auto_20200729_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='title5_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title5_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title5_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title5_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title5_5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
